#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - jq
users:
  - name: communitas
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD0H91SZIFP6rBe3+996fuIeC9e7GYrb885f2xZQkH+8rgG5Zmq+HqIpQ7XgvAGBePjtdKsg58eQktA7vE8UMbCHMVofnCe8mLf3WiaoajMJr+FrSnlau0RkMHIJcdgFDtJcFr5wottqMXsEThUtNBC98eMu8rE1uW8cl7ZLH6H9z2y51uAW04OA0KGHCgSQqOb+pCvFQkdm9hNFVar+/4sPGW6fA6ZWlc1n/cvn3pcCSMJIVpx45TRBa43YktUsMUm3fWrPk4ZWPbjMdUNndDjrAPoCG4nySB9ZE3Z++AEYXkwzvMkhNRc1MykVcyvg3sre/RP/iXwSF6gNsKVe9cioyikv6E4GjooOTCi+OL33ou4hhLvh7GVVhuAy6tDHgkuuubLtatZSuglVIpGmai2+0W39qA6zlgnvgvwYd55baQ01UjbTlacDFEXcjXTBETzpHlXqKwyiuzcs7NFPrurIH7j55VDhmInCVHbb8wXg/5J6dAM+U614HMHgyqu12c=
runcmd:
  - sysctl -w net.core.rmem_max=2500000
  - PORT=$(shuf -i 20000-60999 -n 1)
  - echo "COMMUNITAS_QUIC_PORT=$PORT" | tee /etc/communitas-port.env
  - ufw allow "$PORT"/udp
  - ufw allow "$PORT"/tcp
  - ufw allow 22/tcp
  - ufw --force enable
  - mkdir -p /opt/communitas/bin /var/lib/communitas
  - chown communitas:communitas /opt/communitas /var/lib/communitas
  - printf '%s\n' "[update]\nchannel=stable\n" > /etc/communitas/update.toml
  - |
    set -e
    OWNER=${COMMUNITAS_UPDATE_REPO_OWNER:-dirvine}
    NAME=${COMMUNITAS_UPDATE_REPO_NAME:-communitas}
    TAG=${COMMUNITAS_RELEASE_TAG:-latest}
    API_URL="https://api.github.com/repos/${OWNER}/${NAME}/releases"
    if [ "$TAG" = "latest" ]; then
      REL_JSON=$(curl -sSL "${API_URL}/latest")
    else
      REL_JSON=$(curl -sSL "${API_URL}/tags/${TAG}")
    fi
    ASSET_URL=$(echo "$REL_JSON" | jq -r '.assets[] | select(.name | test("communitas-headless-x86_64-unknown-linux-gnu\\.tar\\.gz$")) | .browser_download_url' | head -n1)
    cd /tmp
    if [ -n "$ASSET_URL" ] && [ "$ASSET_URL" != "null" ]; then
      echo "Downloading: $ASSET_URL"
      if curl -fL "$ASSET_URL" -o communitas-headless-x86_64-unknown-linux-gnu.tar.gz; then
        tar -xzf communitas-headless-x86_64-unknown-linux-gnu.tar.gz
        install -m 0755 communitas-headless /opt/communitas/bin/communitas-headless
        chown communitas:communitas /opt/communitas/bin/communitas-headless
      else
        echo "Download failed; will build from source" >&2
      fi
    else
      echo "No release asset found for ${TAG}; will build from source" >&2
    fi
    if [ ! -x /opt/communitas/bin/communitas-headless ]; then
      # Fallback: build from source
      echo "Building headless from source fallback"
      apt-get update && apt-get install -y build-essential pkg-config libssl-dev curl git
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      git clone https://github.com/${OWNER}/${NAME}.git /tmp/communitas-src
      cd /tmp/communitas-src
      if [ "$TAG" != "latest" ]; then git fetch --tags && git checkout "$TAG" || true; fi
      COMMUNITAS_SKIP_TAURI_BUILD=1 cargo build --release --no-default-features --bin communitas-headless
      install -m 0755 target/release/communitas-headless /opt/communitas/bin/communitas-headless
      chown communitas:communitas /opt/communitas/bin/communitas-headless
    fi
  - |
    cat >/etc/systemd/system/communitas.service <<EOF
    [Unit]
    Description=Communitas Headless QUIC
    After=network-online.target
    Wants=network-online.target

    [Service]
    User=root
    EnvironmentFile=/etc/communitas-port.env
    Environment=RUST_LOG=info,communitas=debug,saorsa_core=info
    ExecStart=/opt/communitas/bin/communitas-headless --config /etc/communitas/config.toml --listen 0.0.0.0:${COMMUNITAS_QUIC_PORT} --metrics --metrics-addr 127.0.0.1:9600
    Restart=always
    RestartSec=5
    LimitNOFILE=1048576

    [Install]
    WantedBy=multi-user.target
    EOF
  - |
    cat >/etc/systemd/system/communitas-updater.service <<'EOF'
    [Unit]
    Description=Communitas periodic self-update (via GitHub Releases)
    After=network-online.target
    Wants=network-online.target

    [Service]
    Type=oneshot
    EnvironmentFile=-/etc/communitas-port.env
    Environment=COMMUNITAS_UPDATE_REPO_OWNER=%E{COMMUNITAS_UPDATE_REPO_OWNER}
    Environment=COMMUNITAS_UPDATE_REPO_NAME=%E{COMMUNITAS_UPDATE_REPO_NAME}
    ExecStart=/bin/bash -lc 'out=$(/opt/communitas/bin/communitas-headless --self-update || true); echo "$out"; if echo "$out" | grep -q "^updated-to="; then systemctl restart communitas; fi'

    [Install]
    WantedBy=multi-user.target
    EOF
  - |
    cat >/etc/systemd/system/communitas-updater.timer <<'EOF'
    [Unit]
    Description=Run Communitas self-update daily

    [Timer]
    OnCalendar=daily
    Persistent=true

    [Install]
    WantedBy=timers.target
    EOF
  - systemctl daemon-reload
  - systemctl enable communitas
  - systemctl start communitas
  - systemctl enable communitas-updater.timer
  - systemctl start communitas-updater.timer
