version: '3.8'

services:
  # Bootstrap node - first node that others connect to
  bootstrap:
    image: communitas-test:latest
    container_name: communitas-bootstrap
    command: ["/app/bootstrap"]
    ports:
      - "8080:8080"  # Bootstrap service port
      - "8081:8081"  # P2P communication port
    environment:
      - RUST_LOG=debug
      - BOOTSTRAP_PORT=8080
      - P2P_PORT=8081
      - NODE_TYPE=bootstrap
      - DATA_DIR=/app/data/bootstrap
    volumes:
      - ./data/bootstrap:/app/data/bootstrap
    networks:
      - communitas-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Node 1 - connects to bootstrap
  node1:
    image: communitas-test:latest
    container_name: communitas-node1
    command: ["/app/communitas-node"]
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "8082:8082"  # Node service port
      - "8083:8083"  # P2P communication port
    environment:
      - RUST_LOG=debug
      - NODE_PORT=8082
      - P2P_PORT=8083
      - BOOTSTRAP_ADDR=bootstrap:8080
      - NODE_TYPE=node
      - NODE_ID=node1
      - DATA_DIR=/app/data/node1
    volumes:
      - ./data/node1:/app/data/node1
    networks:
      - communitas-net

  # Node 2 - connects to bootstrap
  node2:
    image: communitas-test:latest
    container_name: communitas-node2
    command: ["/app/communitas-node"]
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "8084:8084"  # Node service port
      - "8085:8085"  # P2P communication port
    environment:
      - RUST_LOG=debug
      - NODE_PORT=8084
      - P2P_PORT=8085
      - BOOTSTRAP_ADDR=bootstrap:8080
      - NODE_TYPE=node
      - NODE_ID=node2
      - DATA_DIR=/app/data/node2
    volumes:
      - ./data/node2:/app/data/node2
    networks:
      - communitas-net

  # Node 3 - connects to bootstrap
  node3:
    image: communitas-test:latest
    container_name: communitas-node3
    command: ["/app/communitas-node"]
    depends_on:
      bootstrap:
        condition: service_healthy
    ports:
      - "8086:8086"  # Node service port
      - "8087:8087"  # P2P communication port
    environment:
      - RUST_LOG=debug
      - NODE_PORT=8086
      - P2P_PORT=8087
      - BOOTSTRAP_ADDR=bootstrap:8080
      - NODE_TYPE=node
      - NODE_ID=node3
      - DATA_DIR=/app/data/node3
    volumes:
      - ./data/node3:/app/data/node3
    networks:
      - communitas-net

networks:
  communitas-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  bootstrap_data:
  node1_data:
  node2_data:
  node3_data: